ODY-267 Add Add MainCardWithMoneyResult.tsx (Only UI)
daydule/odyssey-mobile pull request #20
Opened 2024-02-03 02:48 UTC by atoook

# 事前確認(共通)

- [ ] PR 前に動作確認をしたか
- [ ] ビルドエラー/ESLint エラーは起きていないか
- [ ] [開発ルール](https://daydule.atlassian.net/wiki/spaces/DAYDULE/pages/9765029)を守って実装しているか
- [ ] 単体テストが全て OK になっているか
- [ ] 機密情報を含んでいないか
- [ ] 最新の`develop`ブランチを反映しているか

# レビュー優先度（どれか一つ）

- [ ] すぐ見てもらいたい
- [ ] 3 日くらいで見てもらいたい
- [ ] 7 日くらいで見てもらいたい

# レビューの度合い

- [ ] コードをぱっと確認してもらいたい
- [ ] コードをぱっと確認 & 動作確認してもらいたい
- [ ] コードをしっかり確認 & 動作確認してもらいたい

# レビュワーによる動作確認

- [ ] @tom-takeru 
- [ ] @Mellbrother 
- [ ] @kzk27 

# やったこと
- MainCardWithMoneyResultコンポーネントと対応するストーリーの作成

# やらないこと
- 金額取得箇所の実装
特になし

# 懸念点や注意点

特になし

# その他

特になし

2024-02-03 06:45 UTC, tom-takeru commented on .storybook/storybook.requires.js
このファイルは.gitignoreに入れたんですが、反応してないみたいですね、、、。
develop branchのマージ前に作成・変更していたためっぽいですね。
ファイルを削除してcommitしてもらっても良いですか？
以降はgitからは無視されると思います！

#### 背景

このファイルは　https://github.com/daydule/odyssey-mobile/blob/29b8de5525558c1868572898a643b20364ec60c1/package.json#L16 
のコマンドで自動生成されます！
そのためgit管理対象から外しました！

2024-02-03 07:08 UTC, tom-takeru requested changes
@atoook 
レビューしました！
ご確認をお願いします 🙏 
(PRのタイトルに Add が2つあったので直しておきました！)

2024-02-03 07:08 UTC, tom-takeru commented on .storybook/storybook.requires.js
このファイルは.gitignoreに入れたんですが、反応してないみたいですね、、、。
develop branchのマージ前に作成・変更していたためっぽいですね。
ファイルを削除してcommitしてもらっても良いですか？
以降はgitからは無視されると思います！

#### 背景

このファイルは　https://github.com/daydule/odyssey-mobile/blob/29b8de5525558c1868572898a643b20364ec60c1/package.json#L16 
のコマンドで自動生成されます！
そのためgit管理対象から外しました！

2024-02-03 07:08 UTC, tom-takeru commented on components/tree/MainCardWithMoneyResult.stories.tsx
> +
@Mellbrother によると以下のような書き方の方が良いようです！

```tsx
type Story = StoryObj<typeof MainCardWithInputMeta> & { args: ComponentProps<typeof MainCardWithMoneyResult> };

export const Default: Story = {
  args: {},
};
```

※これだけでなく、import部分にも変更が必要です！

2024-02-03 07:08 UTC, tom-takeru commented on components/tree/MainCardWithMoneyResult.tsx
> +        <Text style={styles.differencePriceText}> 差額：¥ {difference || '---'}</Text>
`difference`の値が0のとき、 `||` だと `---` が表示されてしまうと思いました！
ここと`previousPrice`, `mainPrice` では `??` を使うのはどうでしょうか？

#### サンプルコード

```
// || の例
console.log(0 || "default"); // "default"
console.log(false || "default"); // "default"
console.log("hello" || "default"); // "hello"

// ?? の例
console.log(0 ?? "default"); // 0
console.log(null ?? "default"); // "default"
console.log(undefined ?? "default"); // "default"
console.log("hello" ?? "default"); // "hello"
```

2024-02-03 07:08 UTC, tom-takeru commented on components/tree/MainCardWithMoneyResult.tsx
> +        <Text style={styles.differencePriceText}> 差額：¥ {difference || '---'}</Text>
```suggestion
        <Text style={styles.mainPriceText}> ¥ {mainPrice ?? 0}</Text>
        <Text style={styles.previousPriceText}> 前回：¥ {previousPrice ?? '---'}</Text>
        <Text style={styles.differencePriceText}> 差額：¥ {difference ?? '---'}</Text>
```

> [!WARNING]
> 「remote repository上でcommit→ローカルで開発」とする場合は、ローカル作業の前のpullを忘れずに！

2024-02-04 08:35 UTC, atoook commented on components/tree/MainCardWithMoneyResult.tsx
> +        <Text style={styles.differencePriceText}> 差額：¥ {difference || '---'}</Text>
そうですね、金額差が０円の時に<code>---</code>だとまずいので、提案いただいた通り修正しました。

2024-02-04 08:40 UTC, atoook commented on .storybook/storybook.requires.js
removeするの忘れてました。指摘ありがとうございます！

2024-02-05 01:32 UTC, tom-takeru approved these changes
LGTM！ 🍦

2024-02-05 05:06 UTC, merged